"""Training module for generative models."""

from artifex.generative_models.training.gradient_accumulation import (
    DynamicLossScaler,
    DynamicLossScalerConfig,
    GradientAccumulator,
    GradientAccumulatorConfig,
)
from artifex.generative_models.training.loops import (
    create_data_pipeline,
    train_epoch_staged,
    train_epoch_streaming,
)
from artifex.generative_models.training.optimizers import create_optimizer
from artifex.generative_models.training.rl import (
    ClippedReward,
    CompositeReward,
    compute_clipped_surrogate_loss,
    compute_discounted_returns,
    compute_gae_advantages,
    compute_kl_divergence,
    compute_masked_clipped_surrogate_loss,
    compute_masked_kl_divergence,
    compute_masked_policy_entropy,
    compute_policy_entropy,
    ConstantReward,
    DPOConfig,
    DPOTrainer,
    GeneratedBatch,
    GeneratedSequenceBatch,
    GenerationRequest,
    GroupRolloutBatch,
    GRPOConfig,
    GRPOTrainer,
    IterativeGenerationBackend,
    IterativeGenerationBatch,
    IterativeGenerationRequest,
    IterativePolicyAdapter,
    LocalSequenceGenerationBackend,
    LocalSequenceRolloutBackend,
    LogProbScorer,
    masked_mean,
    masked_normalize,
    normalize_advantages,
    PolicyAdapter,
    PPOConfig,
    PPOTrainer,
    PreferenceBatch,
    REINFORCEConfig,
    REINFORCETrainer,
    RewardFunction,
    RewardModel,
    ScaledReward,
    SequenceGenerationBackend,
    SequenceGenerationRequest,
    SequencePolicyAdapter,
    SequenceRolloutBackend,
    SequenceRolloutBatch,
    SequenceRolloutPolicyAdapter,
    SequenceRolloutValueAdapter,
    SequenceValueHeadAdapter,
    ThresholdReward,
    TrajectoryBatch,
    ValueAdapter,
)
from artifex.generative_models.training.schedulers import create_scheduler
from artifex.generative_models.training.trainer import Trainer


__all__ = [
    "Trainer",
    "create_optimizer",
    "create_scheduler",
    # High-performance training loops
    "create_data_pipeline",
    "train_epoch_staged",
    "train_epoch_streaming",
    # Gradient accumulation and loss scaling
    "GradientAccumulator",
    "GradientAccumulatorConfig",
    "DynamicLossScaler",
    "DynamicLossScalerConfig",
    # RL Training
    "REINFORCEConfig",
    "REINFORCETrainer",
    "PPOConfig",
    "PPOTrainer",
    "GRPOConfig",
    "GRPOTrainer",
    "DPOConfig",
    "DPOTrainer",
    "SequencePolicyAdapter",
    "SequenceValueHeadAdapter",
    "RewardFunction",
    "ConstantReward",
    "CompositeReward",
    "ThresholdReward",
    "ScaledReward",
    "ClippedReward",
    # Typed RL contracts
    "TrajectoryBatch",
    "GenerationRequest",
    "GeneratedBatch",
    "GeneratedSequenceBatch",
    "SequenceRolloutBatch",
    "PreferenceBatch",
    "GroupRolloutBatch",
    "SequenceGenerationRequest",
    "IterativeGenerationRequest",
    "IterativeGenerationBatch",
    "PolicyAdapter",
    "LogProbScorer",
    "SequenceGenerationBackend",
    "IterativeGenerationBackend",
    "IterativePolicyAdapter",
    "SequenceRolloutBackend",
    "SequenceRolloutPolicyAdapter",
    "SequenceRolloutValueAdapter",
    "ValueAdapter",
    "RewardModel",
    "LocalSequenceGenerationBackend",
    "LocalSequenceRolloutBackend",
    "compute_discounted_returns",
    "compute_gae_advantages",
    "normalize_advantages",
    "masked_mean",
    "masked_normalize",
    "compute_policy_entropy",
    "compute_masked_policy_entropy",
    "compute_kl_divergence",
    "compute_masked_kl_divergence",
    "compute_clipped_surrogate_loss",
    "compute_masked_clipped_surrogate_loss",
]
